### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by psobolewskiPhD** [amirmasoudabdol/sfthemes#2]
These links in the README.md are broken:
1. First paragraph, "Read more <here>."
2. Quick Start: "...color palettes can be found <here>"
3. Accessible Colors: "The <Colors> article..."
4. Scaling: "The <Size Classes> article"

Not sure if they should remotely link to the sfthemes page articles at:
https://sfthemes.amirmasoudabdol.name
Or if the should be relative links to vignettes/

**Comment by amirmasoudabdol** [comment]
Thanks for reporting these! 

Yes, you are right, they are supposed to dynamically link to vignettes pages in the pkgodnw website, and GitHub README doesn't really play nicely with that. I'll see what I can do, maybe I should use the full URL.
