### ISSUE TITLE
Legend title is not Inter

### ISSUE THREAD

**Issue by psobolewskiPhD** [amirmasoudabdol/sfthemes#3]
I used the example code:
```
ggplot(mtcars) +
   geom_point(aes(x = wt, y = mpg, colour = factor(gear))) +
   labs(title = "Fuel Economy",
        subtitle = "Fuel economy declines as weight increases, 1973-74",
        caption = "Data from the 1974 Motor Trend US magazine.",
        x = "Weight (1000 lbs)",
        y = "MPG",
        colour = "Gears") +
   facet_grid(vs ~ am) +
   sf_set_inter(theme_linedraw()) +
   scale_colour_ios_light()

```
On Mac OS Big Sur (M1) with Inter installed:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/76622105/105088091-b6e7b000-5a9b-11eb-840f-bd06218c8a93.png">
Everything looks good, but the legend title.
![plot](https://user-images.githubusercontent.com/76622105/105088123-c4049f00-5a9b-11eb-9fb6-bab1b5312fc7.png)
It looks like Extra Bold and Light work, but Bold doesn't?
Odd.

**Comment by psobolewskiPhD** [comment]
Bizarrely, other Inter options, like Black or Extra Bold work using:
`theme(legend.title = element_text(family = "Inter Black"))`
but not "Inter Bold" nor "Inter Italic"
In fact, I can't get any Italic to work...

**Comment by amirmasoudabdol** [comment]
This is interesting and strange! I think I have an idea what’s going on! 🤔 I can look into it on the weekend! 

For the italic, what if you use `face = “italic”` in your `element_text` specification?

**Comment by psobolewskiPhD** [comment]
Using:
```
ggplot(mtcars) +
   geom_point(aes(x = wt, y = mpg, colour = factor(gear))) +
   labs(title = "Fuel Economy",
        subtitle = "Fuel economy declines as weight increases, 1973-74",
        caption = "Data from the 1974 Motor Trend US magazine.",
        x = "Weight (1000 lbs)",
        y = "MPG",
        colour = "Gears") +
   facet_grid(vs ~ am) +
   sf_set_inter(theme_linedraw()) +
   scale_colour_ios_light()+theme(legend.title = element_text(face = "italic"))

```
does give italic, but not Inter:
![plot](https://user-images.githubusercontent.com/76622105/105094346-717bb080-5aa4-11eb-9d63-c23dfd4a932f.png)

**Comment by psobolewskiPhD** [comment]
So forcing it works, with either:
`+theme(legend.title = element_text(face = "italic", family = "Inter"))
`
or
`theme(legend.title = element_text(face = "bold", family = "Inter"))
`
But that's not using "Inter Italic" nor "Inter Bold" I don't think?

**Comment by amirmasoudabdol** [comment]
I see. Would you please attach a screenshot of the detail panel of the Fonts.app when you have “Inter Bold Italic” selected? I wondering what is your font’s name and alias? Another question, I don’t think you have used the `import_inter()`, have you?

**Comment by psobolewskiPhD** [comment]
For the record, using:

```R
ggplot(mtcars) +
   geom_point(aes(x = wt, y = mpg, colour = factor(gear))) +
   labs(title = "Fuel Economy",
        subtitle = "Fuel economy declines as weight increases, 1973-74",
        caption = "Data from the 1974 Motor Trend US magazine.",
        x = "Weight (1000 lbs)",
        y = "MPG",
        colour = "Gears") +
   facet_grid(vs ~ am) +theme_sf_light(font_family = "Fira Sans")
```

also works:
![plot](https://user-images.githubusercontent.com/76622105/105095084-81e05b00-5aa5-11eb-8a7d-8617f3f5bc3a.png)
but with no 'font_family'—should default to Inter—it's just the legend that's a serif.

**Comment by psobolewskiPhD** [comment]
What do you meant by "Detail" panel?

I did try 'import_inter()'. Output:
```
r$> import_inter()                                                                                                                            
Inter fonts are installed in your R enviroments; however, different OSes handle fonts managements differently. So, I highly recommend manually installing them on your system.

You can find them in /opt/homebrew/lib/R/4.0/site-library/sfthemes/fonts/Inter
```
All the above is after that command...

Is this detail?
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/76622105/105095739-5873ff00-5aa6-11eb-92a3-ed120c74a29a.png">

**Comment by amirmasoudabdol** [comment]
Ok, I think my guess is correct then! I must have missed one of the variables but I think I need to change the way I set the fonts as well. As I mentioned in the documentation, there might have be some issues with the fonts! 😅 Luckily, this seems to be an easy one to solve! 🤞🏼 

Yes, that’s the screenshot I was looking for! 👍🏼 

Thanks for your updates, and investigation. This is very helpful! 😊

**Comment by psobolewskiPhD** [comment]
Thank you—I really dig the theme and functionality!
FYI: I might try my hand at modifying the options to yield dashed lines for y grids and to make minor grids optional... that and the odd axis label offset? It's not the experimental one...
<img width="41" alt="image" src="https://user-images.githubusercontent.com/76622105/105096342-34fd8400-5aa7-11eb-8260-69cbc4d6ec13.png">

**Comment by amirmasoudabdol** [comment]
That was supposed to be a feature but I think I didn't get it quite right! I perhaps should revert it and use a default offset. 😅

**Comment by psobolewskiPhD** [comment]
Also, I'm not sure I'm sold on the title not being fully left justified (with the axis label)...
...and maybe I'd rather the caption text being right justified?
I think i'm going to try to find some time to learn how to play around with the theme() settings...
I like the clean(er) look of: https://github.com/vankesteren/firatheme
...but not the centered titles! (to be fair I rarely use titles on my plots...)

**Comment by amirmasoudabdol** [comment]
I've investigated this, and unfortunately, I couldn't replicate your issue. I was thinking that the issue is due to sfthemes setting the font filenames explicitly, but that was not it!

I've seen report on M1 machines dealing with fonts slightly differently, so, it could very well be that. I think we will have more info about that soon! In the meantime, if I manage to solve this, I'll let you know! 😄

**Comment by psobolewskiPhD** [comment]
Thanks!
It's not a big deal—I don't normally show legends on my own plots, just due to the data they present. It is a bit odd that it's just that one bit that misbehaves...but my setup is certainly not typical, what with M1 mac, R from homebrew, using VS Code, and running httpgd.
I''ll play around with the theme more, might even fork it, when I get more time in Feb.

**Comment by psobolewskiPhD** [comment]
Shit! Sorry! It's not your bug!
Using ggsave() I get the proper font in the png:
![test](https://user-images.githubusercontent.com/76622105/106392030-83d4e300-63f0-11eb-8cdb-509c514e8cab.png)
But if I save from httpgd then the legend isn't Inter:
![plot](https://user-images.githubusercontent.com/76622105/106392074-96e7b300-63f0-11eb-8e4e-bc8129589559.png)

I'll report this as an issue to {httpgd}.
